name: Test
on:
  push:
    branches: master
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    container: projectserum/build:v0.26.0

    steps:
      - uses: actions/checkout@v4

      - name: Generate new keygen
        run: solana-keygen new --no-bip39-passphrase 
      - name: Set url
        run: solana config set --url d
      - name: Install dependencies
        run: yarn install

      - uses: nick-fields/retry@v2
        with:
          timeout_minutes: 120
          max_attempts: 3
          command: |
            solana airdrop 1
            yarn test