name: Test
on:
  push:
    branches: master
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    container: projectserum/build:v0.26.0

    steps:
      - uses: actions/checkout@v3

      - name: Generate new keygen
        run: solana-keygen new --no-bip39-passphrase 
      - name: Set url
        run: solana config set --url d
      - name: Airdrop
        run: solana airdrop 1
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn test